spring:
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: https://www.google.com/
          predicates:
            - Query=url, google
        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
